import 'package:country_pickers/country.dart';

final List<Country> countryList = [
  Country(
    isoCode: "AF",
    phoneCode: "93",
    name: "Afghanistan",
    nameLocalized: "Afghanestan افغانستان",
    iso3Code: "AFG",
  ),
  Country(
    isoCode: "AL",
    phoneCode: "355",
    name: "Albania",
    nameLocalized: "Shqipëria",
    iso3Code: "ALB",
  ),
  Country(
    isoCode: "DZ",
    phoneCode: "213",
    name: "Algeria",
    nameLocalized: "Dzayer ⴷⵣⴰⵢⴻⵔ Al-Jazā'ir الجزائر",
    iso3Code: "DZA",
  ),
  Country(
    isoCode: "AS",
    phoneCode: "1-684",
    name: "American Samoa",
    nameLocalized: "Amerika Sāmoa",
    iso3Code: "ASM",
  ),
  Country(
    isoCode: "AD",
    phoneCode: "376",
    name: "Andorra",
    nameLocalized: "Andorra",
    iso3Code: "AND",
  ),
  Country(
    isoCode: "AO",
    phoneCode: "244",
    name: "Angola",
    nameLocalized: "Ngola",
    iso3Code: "AGO",
  ),
  Country(
    isoCode: "AI",
    phoneCode: "1-264",
    name: "Anguilla",
    nameLocalized: "Anguilla",
    iso3Code: "AIA",
  ),
  Country(
    isoCode: "AQ",
    phoneCode: "672",
    name: "Antarctica",
    nameLocalized:"",
    iso3Code: "ATA",
  ),
  Country(
    isoCode: "AG",
    phoneCode: "1-268",
    name: "Antigua and Barbuda",
    nameLocalized: "Antigua and Barbuda",
    iso3Code: "ATG",
  ),
  Country(
    isoCode: "AR",
    phoneCode: "54",
    name: "Argentina",
    nameLocalized: "Argentina",
    iso3Code: "ARG",
  ),
  Country(
    isoCode: "AM",
    phoneCode: "374",
    name: "Armenia",
    nameLocalized: "Hayastán Հայաստան",
    iso3Code: "ARM",
  ),
  Country(
    isoCode: "AW",
    phoneCode: "297",
    name: "Aruba",
    nameLocalized: "Aruba",
    iso3Code: "ABW",
  ),
  Country(
    isoCode: "AU",
    phoneCode: "61",
    name: "Australia",
    nameLocalized: "Australia",
    iso3Code: "AUS",
  ),
  Country(
    isoCode: "AT",
    phoneCode: "43",
    name: "Austria",
    nameLocalized: "Österreich",
    iso3Code: "AUT",
  ),
  Country(
    isoCode: "AZ",
    phoneCode: "994",
    name: "Azerbaijan",
    nameLocalized: "Azərbaycan",
    iso3Code: "AZE",
  ),
  Country(
    isoCode: "BS",
    phoneCode: "1-242",
    name: "Bahamas",
    nameLocalized: "Bahamas",
    iso3Code: "BHS",
  ),
  Country(
    isoCode: "BH",
    phoneCode: "973",
    name: "Bahrain",
    nameLocalized: "Al-Baḥrayn البحرين",
    iso3Code: "BHR",
  ),
  Country(
    isoCode: "BD",
    phoneCode: "880",
    name: "Bangladesh",
    nameLocalized: "Bangladesh বাংলাদেশ",
    iso3Code: "BGD",
  ),
  Country(
    isoCode: "BB",
    phoneCode: "1-246",
    name: "Barbados",
    nameLocalized: "Barbados",
    iso3Code: "BRB",
  ),
  Country(
    isoCode: "BY",
    phoneCode: "375",
    name: "Belarus",
    nameLocalized: "Bielaruś Беларусь",
    iso3Code: "BLR",
  ),
  Country(
    isoCode: "BE",
    phoneCode: "32",
    name: "Belgium",
    nameLocalized: "België",
    iso3Code: "BEL",
  ),
  Country(
    isoCode: "BZ",
    phoneCode: "501",
    name: "Belize",
    nameLocalized: "Belize",
    iso3Code: "BLZ",
  ),
  Country(
    isoCode: "BJ",
    phoneCode: "229",
    name: "Benin",
    nameLocalized: "Bénin",
    iso3Code: "BEN",
  ),
  Country(
    isoCode: "BM",
    phoneCode: "1-441",
    name: "Bermuda",
    nameLocalized: "Bermuda",
    iso3Code: "BMU",
  ),
  Country(
    isoCode: "BT",
    phoneCode: "975",
    name: "Bhutan",
    nameLocalized:"Druk Yul འབྲུག་ཡུལ",
    iso3Code: "BTN",
  ),
  Country(
    isoCode: "BO",
    phoneCode: "591",
    name: "Bolivia, Plurinational State of",
    nameLocalized: "Bolivia Buliwya Wuliwya Volívia",
    iso3Code: "BOL",
  ),
  Country(
    isoCode: "BA",
    phoneCode: "387",
    name: "Bosnia and Herzegovina",
    nameLocalized: "Bosna i Hercegovina Босна и Херцеговина",
    iso3Code: "BIH",
  ),
  Country(
    isoCode: "BW",
    phoneCode: "267",
    name: "Botswana",
    nameLocalized: "Botswana",
    iso3Code: "BWA",
  ),
  Country(
    isoCode: "BV",
    phoneCode: "47",
    name: "Bouvet Island",
    nameLocalized:"",
    iso3Code: "BVT",
  ),
  Country(
    isoCode: "BR",
    phoneCode: "55",
    name: "Brazil",
    nameLocalized: "Brasil",
    iso3Code: "BRA",
  ),
  Country(
    isoCode: "IO",
    phoneCode: "246",
    name: "British Indian Ocean Territory",
    nameLocalized:"",
    iso3Code: "IOT",
  ),
  Country(
    isoCode: "BN",
    phoneCode: "673",
    name: "Brunei Darussalam",
    nameLocalized: "Brunei بروني",
    iso3Code: "BRN",
  ),
  Country(
    isoCode: "BG",
    phoneCode: "359",
    name: "Bulgaria",
    nameLocalized: "Bălgarija България",
    iso3Code: "BGR",
  ),
  Country(
    isoCode: "BF",
    phoneCode: "226",
    name: "Burkina Faso",
    nameLocalized: "Burkina Faso",
    iso3Code: "BFA",
  ),
  Country(
    isoCode: "BI",
    phoneCode: "257",
    name: "Burundi",
    nameLocalized: "Uburundi",
    iso3Code: "BDI",
  ),
  Country(
    isoCode: "KH",
    phoneCode: "855",
    name: "Cambodia",
    nameLocalized: "Kampuchea កម្ពុជា",
    iso3Code: "KHM",
  ),
  Country(
    isoCode: "CM",
    phoneCode: "237",
    name: "Cameroon",
    nameLocalized: "Cameroun",
    iso3Code: "CMR",
  ),
  Country(
    isoCode: "CA",
    phoneCode: "1",
    name: "Canada",
    nameLocalized: "Canada",
    iso3Code: "CAN",
  ),
  Country(
    isoCode: "CV",
    phoneCode: "238",
    name: "Cape Verde",
    nameLocalized: "Cabo Verde",
    iso3Code: "CPV",
  ),
  Country(
    isoCode: "BQ",
    phoneCode: "599",
    name: "Caribbean Netherlands",
    nameLocalized: "",
    iso3Code: "BES",
  ),
  Country(
    isoCode: "KY",
    phoneCode: "1-345",
    name: "Cayman Islands",
    nameLocalized: "Cayman Islands",
    iso3Code: "CYM",
  ),
  Country(
    isoCode: "CF",
    phoneCode: "236",
    name: "Central African Republic",
    nameLocalized: "Ködörösêse tî Bêafrîka",
    iso3Code: "CAF",
  ),
  Country(
    isoCode: "TD",
    phoneCode: "235",
    name: "Chad",
    nameLocalized: "Tchad Tšād تشاد",
    iso3Code: "TCD",
  ),
  Country(
    isoCode: "CL",
    phoneCode: "56",
    name: "Chile",
    nameLocalized: "Chile",
    iso3Code: "CHL",
  ),
  Country(
    isoCode: "CN",
    phoneCode: "86",
    name: "China",
    nameLocalized: "中国 Zhōngguó",
    iso3Code: "CHN",
  ),
  Country(
    isoCode: "CX",
    phoneCode: "61",
    name: "Christmas Island",
    nameLocalized: "Christmas Island",
    iso3Code: "CXR",
  ),
  Country(
    isoCode: "CC",
    phoneCode: "61",
    name: "Cocos (Keeling) Islands",
    nameLocalized: "Cocos Islands",
    iso3Code: "CCK",
  ),
  Country(
    isoCode: "CO",
    phoneCode: "57",
    name: "Colombia",
    nameLocalized: "Colombia",
    iso3Code: "COL",
  ),
  Country(
    isoCode: "KM",
    phoneCode: "269",
    name: "Comoros",
    nameLocalized: "Komori, جزر القمر ,Comores",
    iso3Code: "COM",
  ),
  Country(
    isoCode: "CG",
    phoneCode: "242",
    name: "Congo",
    nameLocalized: "Republíki ya Kongó",
    iso3Code: "COG",
  ),
  Country(
    isoCode: "CD",
    phoneCode: "243",
    name: "Congo, the Democratic Republic of the",
    nameLocalized: "Republíki ya Kongó Demokratíki",
    iso3Code: "COD",
  ),
  Country(
    isoCode: "CK",
    phoneCode: "682",
    name: "Cook Islands",
    nameLocalized: "Kuki Airani",
    iso3Code: "COK",
  ),
  Country(
    isoCode: "CR",
    phoneCode: "506",
    name: "Costa Rica",
    nameLocalized:"Costa Rica",
    iso3Code: "CRI",
  ),
  Country(
    isoCode: "HR",
    phoneCode: "385",
    name: "Croatia",
    nameLocalized: "Hrvatska",
    iso3Code: "HRV",
  ),
  Country(
    isoCode: "CU",
    phoneCode: "53",
    name: "Cuba",
    nameLocalized: "Cuba",
    iso3Code: "CUB",
  ),
  Country(
    isoCode: "CW",
    phoneCode: "599",
    name: "Curaçao",
    nameLocalized:"Curaçao",
    iso3Code: "CUW",
  ),
  Country(
    isoCode: "CY",
    phoneCode: "357",
    name: "Cyprus",
    nameLocalized:"Kypros, Κύπρος, Kıbrıs",
    iso3Code: "CYP",
  ),
  Country(
    isoCode: "CZ",
    phoneCode: "420",
    name: "Czech Republic",
    nameLocalized: "Česká republika",
    iso3Code: "CZE",
  ),
  Country(
    isoCode: "CI",
    phoneCode: "225",
    name: "Côte d'Ivoire",
    nameLocalized: "Côte d'Ivoire",
    iso3Code: "CIV",
  ),
  Country(
    isoCode: "DK",
    phoneCode: "45",
    name: "Denmark",
    nameLocalized: "Danmark",
    iso3Code: "DNK",
  ),
  Country(
    isoCode: "DJ",
    phoneCode: "253",
    name: "Djibouti",
    nameLocalized:"Jībūtī, جيبوتي ,Djibouti",
    iso3Code: "DJI",
  ),
  Country(
    isoCode: "DM",
    phoneCode: "1-767",
    name: "Dominica",
    nameLocalized: "Dominica",
    iso3Code: "DMA",
  ),
  Country(
    isoCode: "DO",
    phoneCode: "1-849",
    name: "Dominican Republic",
    nameLocalized: "República Dominicana",
    iso3Code: "DOM",
  ),
  Country(
    isoCode: "EC",
    phoneCode: "593",
    name: "Ecuador",
    nameLocalized:"",
    iso3Code: "ECU",
  ),
  Country(
    isoCode: "EG",
    phoneCode: "20",
    name: "Egypt",
    nameLocalized:"",
    iso3Code: "EGY",
  ),
  Country(
    isoCode: "SV",
    phoneCode: "503",
    name: "El Salvador",
    nameLocalized:"",
    iso3Code: "SLV",
  ),
  Country(
    isoCode: "GB-ENG",
    phoneCode: "44",
    name: "England",
    nameLocalized:"",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "GQ",
    phoneCode: "240",
    name: "Equatorial Guinea",
    nameLocalized:"",
    iso3Code: "GNQ",
  ),
  Country(
    isoCode: "ER",
    phoneCode: "291",
    name: "Eritrea",
    nameLocalized:"",
    iso3Code: "ERI",
  ),
  Country(
    isoCode: "EE",
    phoneCode: "372",
    name: "Estonia",
    nameLocalized:"",
    iso3Code: "EST",
  ),
  Country(
    isoCode: "ET",
    phoneCode: "251",
    name: "Ethiopia",
    nameLocalized:"",
    iso3Code: "ETH",
  ),
  Country(
    isoCode: "FK",
    phoneCode: "500",
    name: "Falkland Islands (Malvinas)",
    nameLocalized:"",
    iso3Code: "FLK",
  ),
  Country(
    isoCode: "FO",
    phoneCode: "298",
    name: "Faroe Islands",
    nameLocalized:"",
    iso3Code: "FRO",
  ),
  Country(
    isoCode: "FJ",
    phoneCode: "679",
    name: "Fiji",
    nameLocalized:"",
    iso3Code: "FJI",
  ),
  Country(
    isoCode: "FI",
    phoneCode: "358",
    name: "Finland",
    nameLocalized:"Suomi",
    iso3Code: "FIN",
  ),
  Country(
    isoCode: "FR",
    phoneCode: "33",
    name: "France",
    nameLocalized:"",
    iso3Code: "FRA",
  ),
  Country(
    isoCode: "GF",
    phoneCode: "594",
    name: "French Guiana",
    nameLocalized:"",
    iso3Code: "GUF",
  ),
  Country(
    isoCode: "PF",
    phoneCode: "689",
    name: "French Polynesia",
    nameLocalized:"",
    iso3Code: "PYF",
  ),
  Country(
    isoCode: "TF",
    phoneCode: "262",
    name: "French Southern Territories",
    nameLocalized:"",
    iso3Code: "ATF",
  ),
  Country(
    isoCode: "GA",
    phoneCode: "241",
    name: "Gabon",
    nameLocalized:"",
    iso3Code: "GAB",
  ),
  Country(
    isoCode: "GM",
    phoneCode: "220",
    name: "Gambia",
    nameLocalized:"",
    iso3Code: "GMB",
  ),
  Country(
    isoCode: "GE",
    phoneCode: "995",
    name: "Georgia",
    nameLocalized:"",
    iso3Code: "GEO",
  ),
  Country(
    isoCode: "DE",
    phoneCode: "49",
    name: "Germany",
    nameLocalized:"Deutschland",
    iso3Code: "DEU",
  ),
  Country(
    isoCode: "GH",
    phoneCode: "233",
    name: "Ghana",
    nameLocalized:"",
    iso3Code: "GHA",
  ),
  Country(
    isoCode: "GI",
    phoneCode: "350",
    name: "Gibraltar",
    nameLocalized:"",
    iso3Code: "GIB",
  ),
  Country(
    isoCode: "GR",
    phoneCode: "30",
    name: "Greece",
    nameLocalized:"",
    iso3Code: "GRC",
  ),
  Country(
    isoCode: "GL",
    phoneCode: "299",
    name: "Greenland",
    nameLocalized:"",
    iso3Code: "GRL",
  ),
  Country(
    isoCode: "GD",
    phoneCode: "1-473",
    name: "Grenada",
    nameLocalized:"",
    iso3Code: "GRD",
  ),
  Country(
    isoCode: "GP",
    phoneCode: "590",
    name: "Guadeloupe",
    nameLocalized:"",
    iso3Code: "GLP",
  ),
  Country(
    isoCode: "GU",
    phoneCode: "1-671",
    name: "Guam",
    nameLocalized:"",
    iso3Code: "GUM",
  ),
  Country(
    isoCode: "GT",
    phoneCode: "502",
    name: "Guatemala",
    nameLocalized:"",
    iso3Code: "GTM",
  ),
  Country(
    isoCode: "GG",
    phoneCode: "44-1481",
    name: "Guernsey",
    nameLocalized:"",
    iso3Code: "GGY",
  ),
  Country(
    isoCode: "GN",
    phoneCode: "224",
    name: "Guinea",
    nameLocalized:"",
    iso3Code: "GIN",
  ),
  Country(
    isoCode: "GW",
    phoneCode: "245",
    name: "Guinea-Bissau",
    nameLocalized:"",
    iso3Code: "GNB",
  ),
  Country(
    isoCode: "GY",
    phoneCode: "592",
    name: "Guyana",
    nameLocalized:"",
    iso3Code: "GUY",
  ),
  Country(
    isoCode: "HT",
    phoneCode: "509",
    name: "Haiti",
    nameLocalized:"",
    iso3Code: "HTI",
  ),
  Country(
    isoCode: "HM",
    phoneCode: "672",
    name: "Heard Island and McDonald Islands",
    nameLocalized:"",
    iso3Code: "HMD",
  ),
  Country(
    isoCode: "VA",
    phoneCode: "379",
    name: "Holy See (Vatican City State)",
    nameLocalized:"",
    iso3Code: "VAT",
  ),
  Country(
    isoCode: "HN",
    phoneCode: "504",
    name: "Honduras",
    nameLocalized:"",
    iso3Code: "HND",
  ),
  Country(
    isoCode: "HK",
    phoneCode: "852",
    name: "Hong Kong",
    nameLocalized:"",
    iso3Code: "HKG",
  ),
  Country(
    isoCode: "HU",
    phoneCode: "36",
    name: "Hungary",
    nameLocalized:"",
    iso3Code: "HUN",
  ),
  Country(
    isoCode: "IS",
    phoneCode: "354",
    name: "Iceland",
    nameLocalized:"Ísland",
    iso3Code: "ISL",
  ),
  Country(
    isoCode: "IN",
    phoneCode: "91",
    name: "India",
    nameLocalized:"",
    iso3Code: "IND",
  ),
  Country(
    isoCode: "ID",
    phoneCode: "62",
    name: "Indonesia",
    nameLocalized:"",
    iso3Code: "IDN",
  ),
  Country(
    isoCode: "IR",
    phoneCode: "98",
    name: "Iran, Islamic Republic of",
    nameLocalized:"",
    iso3Code: "IRN",
  ),
  Country(
    isoCode: "IQ",
    phoneCode: "964",
    name: "Iraq",
    nameLocalized:"",
    iso3Code: "IRQ",
  ),
  Country(
    isoCode: "IE",
    phoneCode: "353",
    name: "Ireland",
    nameLocalized:"",
    iso3Code: "IRL",
  ),
  Country(
    isoCode: "IM",
    phoneCode: "44-1624",
    name: "Isle of Man",
    nameLocalized:"",
    iso3Code: "IMN",
  ),
  Country(
    isoCode: "IL",
    phoneCode: "972",
    name: "Israel",
    nameLocalized:"",
    iso3Code: "ISR",
  ),
  Country(
    isoCode: "IT",
    phoneCode: "39",
    name: "Italy",
    nameLocalized: "Italia",
    iso3Code: "ITA",
  ),
  Country(
    isoCode: "JM",
    phoneCode: "1-876",
    name: "Jamaica",
    nameLocalized:"",
    iso3Code: "JAM",
  ),
  Country(
    isoCode: "JP",
    phoneCode: "81",
    name: "Japan",
    nameLocalized:"日本 Nihon",
    iso3Code: "JPN",
  ),
  Country(
    isoCode: "JE",
    phoneCode: "44-1534",
    name: "Jersey",
    nameLocalized:"",
    iso3Code: "JEY",
  ),
  Country(
    isoCode: "JO",
    phoneCode: "962",
    name: "Jordan",
    nameLocalized:"",
    iso3Code: "JOR",
  ),
  Country(
    isoCode: "KZ",
    phoneCode: "7",
    name: "Kazakhstan",
    nameLocalized:"",
    iso3Code: "KAZ",
  ),
  Country(
    isoCode: "KE",
    phoneCode: "254",
    name: "Kenya",
    nameLocalized:"",
    iso3Code: "KEN",
  ),
  Country(
    isoCode: "KI",
    phoneCode: "686",
    name: "Kiribati",
    nameLocalized:"",
    iso3Code: "KIR",
  ),
  Country(
    isoCode: "KP",
    phoneCode: "850",
    name: "Korea, Democratic People's Republic of",
    nameLocalized:"",
    iso3Code: "PRK",
  ),
  Country(
    isoCode: "KR",
    phoneCode: "82",
    name: "Korea, Republic of",
    nameLocalized:"",
    iso3Code: "KOR",
  ),
  Country(
    isoCode: "XK",
    phoneCode: "383",
    name: "Kosovo",
    nameLocalized:"",
    iso3Code: "KOS",
  ),
  Country(
    isoCode: "KW",
    phoneCode: "965",
    name: "Kuwait",
    nameLocalized:"",
    iso3Code: "KWT",
  ),
  Country(
    isoCode: "KG",
    phoneCode: "996",
    name: "Kyrgyzstan",
    nameLocalized:"",
    iso3Code: "KGZ",
  ),
  Country(
    isoCode: "LA",
    phoneCode: "856",
    name: "Lao People's Democratic Republic",
    nameLocalized:"",
    iso3Code: "LAO",
  ),
  Country(
    isoCode: "LV",
    phoneCode: "371",
    name: "Latvia",
    nameLocalized:"",
    iso3Code: "LVA",
  ),
  Country(
    isoCode: "LB",
    phoneCode: "961",
    name: "Lebanon",
    nameLocalized:"",
    iso3Code: "LBN",
  ),
  Country(
    isoCode: "LS",
    phoneCode: "266",
    name: "Lesotho",
    nameLocalized:"",
    iso3Code: "LSO",
  ),
  Country(
    isoCode: "LR",
    phoneCode: "231",
    name: "Liberia",
    nameLocalized:"",
    iso3Code: "LBR",
  ),
  Country(
    isoCode: "LY",
    phoneCode: "218",
    name: "Libya",
    nameLocalized:"",
    iso3Code: "LBY",
  ),
  Country(
    isoCode: "LI",
    phoneCode: "423",
    name: "Liechtenstein",
    nameLocalized:"",
    iso3Code: "LIE",
  ),
  Country(
    isoCode: "LT",
    phoneCode: "370",
    name: "Lithuania",
    nameLocalized:"",
    iso3Code: "LTU",
  ),
  Country(
    isoCode: "LU",
    phoneCode: "352",
    name: "Luxembourg",
    nameLocalized:"",
    iso3Code: "LUX",
  ),
  Country(
    isoCode: "MO",
    phoneCode: "853",
    name: "Macao",
    nameLocalized:"",
    iso3Code: "MAC",
  ),
  Country(
    isoCode: "MK",
    phoneCode: "389",
    name: "Macedonia, the former Yugoslav Republic of",
    nameLocalized:"",
    iso3Code: "MKD",
  ),
  Country(
    isoCode: "MG",
    phoneCode: "261",
    name: "Madagascar",
    nameLocalized:"",
    iso3Code: "MDG",
  ),
  Country(
    isoCode: "MW",
    phoneCode: "265",
    name: "Malawi",
    nameLocalized:"",
    iso3Code: "MWI",
  ),
  Country(
    isoCode: "MY",
    phoneCode: "60",
    name: "Malaysia",
    nameLocalized:"",
    iso3Code: "MYS",
  ),
  Country(
    isoCode: "MV",
    phoneCode: "960",
    name: "Maldives",
    nameLocalized:"",
    iso3Code: "MDV",
  ),
  Country(
    isoCode: "ML",
    phoneCode: "223",
    name: "Mali",
    nameLocalized:"",
    iso3Code: "MLI",
  ),
  Country(
    isoCode: "MT",
    phoneCode: "356",
    name: "Malta",
    nameLocalized:"",
    iso3Code: "MLT",
  ),
  Country(
    isoCode: "MH",
    phoneCode: "692",
    name: "Marshall Islands",
    nameLocalized:"",
    iso3Code: "MHL",
  ),
  Country(
    isoCode: "MQ",
    phoneCode: "596",
    name: "Martinique",
    nameLocalized:"",
    iso3Code: "MTQ",
  ),
  Country(
    isoCode: "MR",
    phoneCode: "222",
    name: "Mauritania",
    nameLocalized:"",
    iso3Code: "MRT",
  ),
  Country(
    isoCode: "MU",
    phoneCode: "230",
    name: "Mauritius",
    nameLocalized:"",
    iso3Code: "MUS",
  ),
  Country(
    isoCode: "YT",
    phoneCode: "262",
    name: "Mayotte",
    nameLocalized:"",
    iso3Code: "MYT",
  ),
  Country(
    isoCode: "MX",
    phoneCode: "52",
    name: "Mexico",
    nameLocalized:"",
    iso3Code: "MEX",
  ),
  Country(
    isoCode: "FM",
    phoneCode: "691",
    name: "Micronesia, Federated States of",
    nameLocalized:"",
    iso3Code: "FSM",
  ),
  Country(
    isoCode: "MD",
    phoneCode: "373",
    name: "Moldova, Republic of",
    nameLocalized:"",
    iso3Code: "MDA",
  ),
  Country(
    isoCode: "MC",
    phoneCode: "377",
    name: "Monaco",
    nameLocalized:"",
    iso3Code: "MCO",
  ),
  Country(
    isoCode: "MN",
    phoneCode: "976",
    name: "Mongolia",
    nameLocalized:"",
    iso3Code: "MNG",
  ),
  Country(
    isoCode: "ME",
    phoneCode: "382",
    name: "Montenegro",
    nameLocalized:"",
    iso3Code: "MNE",
  ),
  Country(
    isoCode: "MS",
    phoneCode: "1-664",
    name: "Montserrat",
    nameLocalized:"",
    iso3Code: "MSR",
  ),
  Country(
    isoCode: "MA",
    phoneCode: "212",
    name: "Morocco",
    nameLocalized:"",
    iso3Code: "MAR",
  ),
  Country(
    isoCode: "MZ",
    phoneCode: "258",
    name: "Mozambique",
    nameLocalized:"",
    iso3Code: "MOZ",
  ),
  Country(
    isoCode: "MM",
    phoneCode: "95",
    name: "Myanmar",
    nameLocalized:"",
    iso3Code: "MMR",
  ),
  Country(
    isoCode: "NA",
    phoneCode: "264",
    name: "Namibia",
    nameLocalized:"",
    iso3Code: "NAM",
  ),
  Country(
    isoCode: "NR",
    phoneCode: "674",
    name: "Nauru",
    nameLocalized:"",
    iso3Code: "NRU",
  ),
  Country(
    isoCode: "NP",
    phoneCode: "977",
    name: "Nepal",
    nameLocalized:"",
    iso3Code: "NPL",
  ),
  Country(
    isoCode: "NL",
    phoneCode: "31",
    name: "Netherlands",
    nameLocalized: "Nederland",
    iso3Code: "NLD",
  ),
  Country(
    isoCode: "AN",
    phoneCode: "599",
    name: "Netherlands Antilles",
    nameLocalized:"",
    iso3Code: "AN",
  ),
  Country(
    isoCode: "NC",
    phoneCode: "687",
    name: "New Caledonia",
    nameLocalized:"",
    iso3Code: "NCL",
  ),
  Country(
    isoCode: "NZ",
    phoneCode: "64",
    name: "New Zealand",
    nameLocalized:"",
    iso3Code: "NZL",
  ),
  Country(
    isoCode: "NI",
    phoneCode: "505",
    name: "Nicaragua",
    nameLocalized:"",
    iso3Code: "NIC",
  ),
  Country(
    isoCode: "NE",
    phoneCode: "227",
    name: "Niger",
    nameLocalized:"",
    iso3Code: "NER",
  ),
  Country(
    isoCode: "NG",
    phoneCode: "234",
    name: "Nigeria",
    nameLocalized:"",
    iso3Code: "NGA",
  ),
  Country(
    isoCode: "NU",
    phoneCode: "683",
    name: "Niue",
    nameLocalized:"",
    iso3Code: "NIU",
  ),
  Country(
    isoCode: "NF",
    phoneCode: "672",
    name: "Norfolk Island",
    nameLocalized:"",
    iso3Code: "NFK",
  ),
  Country(
    isoCode: "GB-NIR",
    phoneCode: "44",
    name: "Northern Ireland",
    nameLocalized:"",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "MP",
    phoneCode: "1-670",
    name: "Northern Mariana Islands",
    nameLocalized:"",
    iso3Code: "MNP",
  ),
  Country(
    isoCode: "NO",
    phoneCode: "47",
    name: "Norway",
    nameLocalized:"Norge",
    iso3Code: "NOR",
  ),
  Country(
    isoCode: "OM",
    phoneCode: "968",
    name: "Oman",
    nameLocalized:"",
    iso3Code: "OMN",
  ),
  Country(
    isoCode: "PK",
    phoneCode: "92",
    name: "Pakistan",
    nameLocalized:"",
    iso3Code: "PAK",
  ),
  Country(
    isoCode: "PW",
    phoneCode: "680",
    name: "Palau",
    nameLocalized:"",
    iso3Code: "PLW",
  ),
  Country(
    isoCode: "PS",
    phoneCode: "970",
    name: "Palestine",
    nameLocalized:"",
    iso3Code: "PSE",
  ),
  Country(
    isoCode: "PA",
    phoneCode: "507",
    name: "Panama",
    nameLocalized:"",
    iso3Code: "PAN",
  ),
  Country(
    isoCode: "PG",
    phoneCode: "675",
    name: "Papua New Guinea",
    nameLocalized:"",
    iso3Code: "PNG",
  ),
  Country(
    isoCode: "PY",
    phoneCode: "595",
    name: "Paraguay",
    nameLocalized:"",
    iso3Code: "PRY",
  ),
  Country(
    isoCode: "PE",
    phoneCode: "51",
    name: "Peru",
    nameLocalized:"",
    iso3Code: "PER",
  ),
  Country(
    isoCode: "PH",
    phoneCode: "63",
    name: "Philippines",
    nameLocalized:"",
    iso3Code: "PHL",
  ),
  Country(
    isoCode: "PN",
    phoneCode: "64",
    name: "Pitcairn",
    nameLocalized:"",
    iso3Code: "PCN",
  ),
  Country(
    isoCode: "PL",
    phoneCode: "48",
    name: "Poland",
    nameLocalized:"",
    iso3Code: "POL",
  ),
  Country(
    isoCode: "PT",
    phoneCode: "351",
    name: "Portugal",
    nameLocalized:"",
    iso3Code: "PRT",
  ),
  Country(
    isoCode: "PR",
    phoneCode: "1-787",
    name: "Puerto Rico",
    nameLocalized:"",
    iso3Code: "PRI",
  ),
  Country(
    isoCode: "QA",
    phoneCode: "974",
    name: "Qatar",
    nameLocalized:"",
    iso3Code: "QAT",
  ),
  Country(
    isoCode: "RO",
    phoneCode: "40",
    name: "Romania",
    nameLocalized:"",
    iso3Code: "ROU",
  ),
  Country(
    isoCode: "RU",
    phoneCode: "7",
    name: "Russian Federation",
    nameLocalized:"",
    iso3Code: "RUS",
  ),
  Country(
    isoCode: "RW",
    phoneCode: "250",
    name: "Rwanda",
    nameLocalized:"",
    iso3Code: "RWA",
  ),
  Country(
    isoCode: "RE",
    phoneCode: "262",
    name: "Réunion",
    nameLocalized:"",
    iso3Code: "REU",
  ),
  Country(
    isoCode: "BL",
    phoneCode: "590",
    name: "Saint Barthélemy",
    nameLocalized:"",
    iso3Code: "BLM",
  ),
  Country(
    isoCode: "SH",
    phoneCode: "290",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    nameLocalized:"",
    iso3Code: "SHN",
  ),
  Country(
    isoCode: "KN",
    phoneCode: "1-869",
    name: "Saint Kitts and Nevis",
    nameLocalized:"",
    iso3Code: "KNA",
  ),
  Country(
    isoCode: "LC",
    phoneCode: "1-758",
    name: "Saint Lucia",
    nameLocalized:"",
    iso3Code: "LCA",
  ),
  Country(
    isoCode: "MF",
    phoneCode: "590",
    name: "Saint Martin",
    nameLocalized:"",
    iso3Code: "MAF",
  ),
  Country(
    isoCode: "PM",
    phoneCode: "508",
    name: "Saint Pierre and Miquelon",
    nameLocalized:"",
    iso3Code: "SPM",
  ),
  Country(
    isoCode: "VC",
    phoneCode: "1-784",
    name: "Saint Vincent and the Grenadines",
    nameLocalized:"",
    iso3Code: "VCT",
  ),
  Country(
    isoCode: "WS",
    phoneCode: "685",
    name: "Samoa",
    nameLocalized:"",
    iso3Code: "WSM",
  ),
  Country(
    isoCode: "SM",
    phoneCode: "378",
    name: "San Marino",
    nameLocalized:"",
    iso3Code: "SMR",
  ),
  Country(
    isoCode: "ST",
    phoneCode: "239",
    name: "Sao Tome and Principe",
    nameLocalized:"",
    iso3Code: "STP",
  ),
  Country(
    isoCode: "SA",
    phoneCode: "966",
    name: "Saudi Arabia",
    nameLocalized:"",
    iso3Code: "SAU",
  ),
  Country(
    isoCode: "GB-SCT",
    phoneCode: "44",
    name: "Scotland",
    nameLocalized:"",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "SN",
    phoneCode: "221",
    name: "Senegal",
    nameLocalized:"",
    iso3Code: "SEN",
  ),
  Country(
    isoCode: "RS",
    phoneCode: "381",
    name: "Serbia",
    nameLocalized:"",
    iso3Code: "SRB",
  ),
  Country(
    isoCode: "SC",
    phoneCode: "248",
    name: "Seychelles",
    nameLocalized:"",
    iso3Code: "SYC",
  ),
  Country(
    isoCode: "SL",
    phoneCode: "232",
    name: "Sierra Leone",
    nameLocalized:"",
    iso3Code: "SLE",
  ),
  Country(
    isoCode: "SG",
    phoneCode: "65",
    name: "Singapore",
    nameLocalized:"",
    iso3Code: "SGP",
  ),
  Country(
    isoCode: "SX",
    phoneCode: "1-721",
    name: "Sint Maarten (Dutch part)",
    nameLocalized:"",
    iso3Code: "SXM",
  ),
  Country(
    isoCode: "SK",
    phoneCode: "421",
    name: "Slovakia",
    nameLocalized:"",
    iso3Code: "SVK",
  ),
  Country(
    isoCode: "SI",
    phoneCode: "386",
    name: "Slovenia",
    nameLocalized:"",
    iso3Code: "SVN",
  ),
  Country(
    isoCode: "SB",
    phoneCode: "677",
    name: "Solomon Islands",
    nameLocalized:"",
    iso3Code: "SLB",
  ),
  Country(
    isoCode: "SO",
    phoneCode: "252",
    name: "Somalia",
    nameLocalized:"",
    iso3Code: "SOM",
  ),
  Country(
    isoCode: "ZA",
    phoneCode: "27",
    name: "South Africa",
    nameLocalized:"",
    iso3Code: "ZAF",
  ),
  Country(
    isoCode: "GS",
    phoneCode: "500",
    name: "South Georgia and the South Sandwich Islands",
    nameLocalized:"",
    iso3Code: "SGS",
  ),
  Country(
    isoCode: "SS",
    phoneCode: "211",
    name: "South Sudan",
    nameLocalized:"",
    iso3Code: "SSD",
  ),
  Country(
    isoCode: "ES",
    phoneCode: "34",
    name: "Spain",
    nameLocalized: "España",
    iso3Code: "ESP",
  ),
  Country(
    isoCode: "LK",
    phoneCode: "94",
    name: "Sri Lanka",
    nameLocalized:"",
    iso3Code: "LKA",
  ),
  Country(
    isoCode: "SD",
    phoneCode: "249",
    name: "Sudan",
    nameLocalized:"",
    iso3Code: "SDN",
  ),
  Country(
    isoCode: "SR",
    phoneCode: "597",
    name: "Suriname",
    nameLocalized:"",
    iso3Code: "SUR",
  ),
  Country(
    isoCode: "SJ",
    phoneCode: "47",
    name: "Svalbard and Jan Mayen Islands",
    nameLocalized:"",
    iso3Code: "SJM",
  ),
  Country(
    isoCode: "SZ",
    phoneCode: "268",
    name: "Swaziland",
    nameLocalized:"",
    iso3Code: "SWZ",
  ),
  Country(
    isoCode: "SE",
    phoneCode: "46",
    name: "Sweden",
    nameLocalized:"Sverige",
    iso3Code: "SWE",
  ),
  Country(
    isoCode: "CH",
    phoneCode: "41",
    name: "Switzerland",
    nameLocalized:"",
    iso3Code: "CHE",
  ),
  Country(
    isoCode: "SY",
    phoneCode: "963",
    name: "Syrian Arab Republic",
    nameLocalized:"",
    iso3Code: "SYR",
  ),
  Country(
    isoCode: "TW",
    phoneCode: "886",
    nameLocalized:"",
    name: "Taiwan",
    iso3Code: "TWN",
  ),
  Country(
    isoCode: "TJ",
    phoneCode: "992",
    name: "Tajikistan",
    nameLocalized:"",
    iso3Code: "TJK",
  ),
  Country(
    isoCode: "TZ",
    phoneCode: "255",
    name: "Tanzania, United Republic of",
    nameLocalized:"",
    iso3Code: "TZA",
  ),
  Country(
    isoCode: "TH",
    phoneCode: "66",
    name: "Thailand",
    nameLocalized:"",
    iso3Code: "THA",
  ),
  Country(
    isoCode: "TL",
    phoneCode: "670",
    name: "Timor-Leste",
    nameLocalized:"",
    iso3Code: "TLS",
  ),
  Country(
    isoCode: "TG",
    phoneCode: "228",
    name: "Togo",
    nameLocalized:"",
    iso3Code: "TGO",
  ),
  Country(
    isoCode: "TK",
    phoneCode: "690",
    name: "Tokelau",
    nameLocalized:"",
    iso3Code: "TKL",
  ),
  Country(
    isoCode: "TO",
    phoneCode: "676",
    name: "Tonga",
    nameLocalized:"",
    iso3Code: "TON",
  ),
  Country(
    isoCode: "TT",
    phoneCode: "1-868",
    name: "Trinidad and Tobago",
    nameLocalized:"",
    iso3Code: "TTO",
  ),
  Country(
    isoCode: "TN",
    phoneCode: "216",
    name: "Tunisia",
    nameLocalized:"",
    iso3Code: "TUN",
  ),
  Country(
    isoCode: "TR",
    phoneCode: "90",
    name: "Turkey",
    nameLocalized:"",
    iso3Code: "TUR",
  ),
  Country(
    isoCode: "TM",
    phoneCode: "993",
    name: "Turkmenistan",
    nameLocalized:"",
    iso3Code: "TKM",
  ),
  Country(
    isoCode: "TC",
    phoneCode: "1-649",
    name: "Turks and Caicos Islands",
    nameLocalized:"",
    iso3Code: "TCA",
  ),
  Country(
    isoCode: "TV",
    phoneCode: "688",
    name: "Tuvalu",
    nameLocalized:"",
    iso3Code: "TUV",
  ),
  Country(
    isoCode: "UG",
    phoneCode: "256",
    name: "Uganda",
    nameLocalized:"",
    iso3Code: "UGA",
  ),
  Country(
    isoCode: "UA",
    phoneCode: "380",
    name: "Ukraine",
    nameLocalized:"",
    iso3Code: "UKR",
  ),
  Country(
    isoCode: "AE",
    phoneCode: "971",
    name: "United Arab Emirates",
    nameLocalized:"",
    iso3Code: "ARE",
  ),
  Country(
    isoCode: "GB",
    phoneCode: "44",
    name: "United Kingdom",
    nameLocalized:"",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "US",
    phoneCode: "1",
    name: "United States",
    nameLocalized:"",
    iso3Code: "USA",
  ),
  Country(
    isoCode: "UY",
    phoneCode: "598",
    name: "Uruguay",
    nameLocalized:"",
    iso3Code: "URY",
  ),
  Country(
    isoCode: "UM",
    phoneCode: "1",
    name: "US Minor Outlying Islands",
    nameLocalized:"",
    iso3Code: "UMI",
  ),
  Country(
    isoCode: "UZ",
    phoneCode: "998",
    name: "Uzbekistan",
    nameLocalized:"",
    iso3Code: "UZB",
  ),
  Country(
    isoCode: "VU",
    phoneCode: "678",
    name: "Vanuatu",
    nameLocalized:"",
    iso3Code: "VUT",
  ),
  Country(
    isoCode: "VE",
    phoneCode: "58",
    name: "Venezuela, Bolivarian Republic of",
    nameLocalized:"",
    iso3Code: "VEN",
  ),
  Country(
    isoCode: "VN",
    phoneCode: "84",
    name: "Vietnam",
    nameLocalized:"",
    iso3Code: "VNM",
  ),
  Country(
    isoCode: "VG",
    phoneCode: "1-284",
    name: "Virgin Islands, British",
    nameLocalized:"",
    iso3Code: "VGB",
  ),
  Country(
    isoCode: "VI",
    phoneCode: "1-340",
    name: "Virgin Islands, U.S.",
    nameLocalized:"",
    iso3Code: "VIR",
  ),
  Country(
    isoCode: "GB-WLS",
    phoneCode: "44",
    name: "Wales",
    nameLocalized:"",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "WF",
    phoneCode: "681",
    name: "Wallis and Futuna Islands",
    nameLocalized:"",
    iso3Code: "WLF",
  ),
  Country(
    isoCode: "EH",
    phoneCode: "212",
    name: "Western Sahara",
    nameLocalized:"",
    iso3Code: "ESH",
  ),
  Country(
    isoCode: "YE",
    phoneCode: "967",
    name: "Yemen",
    nameLocalized:"",
    iso3Code: "YEM",
  ),
  Country(
    isoCode: "ZM",
    phoneCode: "260",
    name: "Zambia",
    nameLocalized:"",
    iso3Code: "ZMB",
  ),
  Country(
    isoCode: "ZW",
    phoneCode: "263",
    name: "Zimbabwe",
    nameLocalized:"",
    iso3Code: "ZWE",
  ),
  Country(
    isoCode: "AX",
    phoneCode: "358",
    name: "Åland Islands",
    nameLocalized: "Ahvenanmaa",
    iso3Code: "ALA",
  ),
];
